package sbtmolecule.db.sqlDialect

import molecule.base.metaModel.MetaAttribute
import molecule.core.dataModel.*

object MSSQLServer extends Dialect {

  override def dbId: String = "MSSQLServer"

  override def tpe(metaAttribute: MetaAttribute, generalProps: Map[String, String] = Map.empty): String = {
    // Priority: 1) Attribute-specific custom property, 2) General custom property, 3) Default
    metaAttribute.dbColumnProps.get(dbId).orElse {
      generalProps.get(metaAttribute.baseTpe)
    }.getOrElse {
      // Use default type mapping
      if (metaAttribute.attribute == "id")
        "BIGINT AUTO_INCREMENT PRIMARY KEY"
      else metaAttribute.value match {
        case OneValue => metaAttribute.baseTpe match {
          case "ID"             => "BIGINT"
          case "String"         => "TEXT"
          case "Int"            => "INT"
          case "Long"           => "BIGINT"
          case "Float"          => "REAL"
          case "Double"         => "REAL"
          case "Boolean"        => "TINYINT(1)"
          case "BigInt"         => "DECIMAL(38)"
          case "BigDecimal"     => "DECIMAL(38, 19)"
          case "Date"           => "BIGINT"
          case "Duration"       => "TINYTEXT"
          case "Instant"        => "TINYTEXT"
          case "LocalDate"      => "TINYTEXT"
          case "LocalTime"      => "TINYTEXT"
          case "LocalDateTime"  => "TINYTEXT"
          case "OffsetTime"     => "TINYTEXT"
          case "OffsetDateTime" => "TINYTEXT"
          case "ZonedDateTime"  => "TINYTEXT"
          case "UUID"           => "TINYTEXT"
          case "URI"            => "TEXT"
          case "Byte"           => "TINYINT"
          case "Short"          => "SMALLINT"
          case "Char"           => "CHAR"
        }
        case _          => "JSON"
      }
    }
  }

  // https://dev.mysql.com/doc/mysqld-version-reference/en/keywords.html
  override def reservedKeyWords: List[String] = List(
    "absolute",
    "action",
    "ada",
    "add",
    "admin",
    "after",
    "aggregate",
    "alias",
    "all",
    "allocate",
    "alter",
    "and",
    "any",
    "are",
    "array",
    "as",
    "asc",
    "asensitive",
    "assertion",
    "asymmetric",
    "at",
    "atomic",
    "authorization",
    "avg",
    "before",
    "begin",
    "between",
    "binary",
    "bit",
    "bit_length",
    "blob",
    "boolean",
    "both",
    "breadth",
    "by",
    "call",
    "called",
    "cardinality",
    "cascade",
    "cascaded",
    "case",
    "cast",
    "catalog",
    "char",
    "char_length",
    "character",
    "character_length",
    "check",
    "class",
    "clob",
    "close",
    "coalesce",
    "collate",
    "collation",
    "collect",
    "column",
    "commit",
    "completion",
    "condition",
    "connect",
    "connection",
    "constraint",
    "constraints",
    "constructor",
    "continue",
    "convert",
    "corr",
    "corresponding",
    "count",
    "covar_pop",
    "covar_samp",
    "create",
    "cross",
    "cube",
    "cume_dist",
    "current",
    "current_catalog",
    "current_date",
    "current_default_transform_group",
    "current_path",
    "current_role",
    "current_schema",
    "current_time",
    "current_timestamp",
    "current_transform_group_for_type",
    "current_user",
    "cursor",
    "cycle",
    "data",
    "date",
    "day",
    "deallocate",
    "dec",
    "decimal",
    "declare",
    "default",
    "deferrable",
    "deferred",
    "delete",
    "depth",
    "deref",
    "desc",
    "describe",
    "descriptor",
    "destroy",
    "destructor",
    "deterministic",
    "diagnostics",
    "dictionary",
    "disconnect",
    "distinct",
    "domain",
    "double",
    "drop",
    "dynamic",
    "each",
    "element",
    "else",
    "end",
    "end -exec",
    "equals",
    "escape",
    "every",
    "except",
    "exception",
    "exec",
    "execute",
    "exists",
    "external",
    "extract",
    "fetch",
    "filter",
    "first",
    "float",
    "for",
    "foreign",
    "fortran",
    "found",
    "free",
    "from",
    "full",
    "fulltexttable",
    "fusion",
    "general",
    "get",
    "global",
    "go",
    "goto",
    "grant",
    "group",
    "grouping",
    "having",
    "hold",
    "host",
    "hour",
    "identity",
    "ignore",
    "immediate",
    "in",
    "include",
    "index",
    "indicator",
    "initialize",
    "initially",
    "inner",
    "inout",
    "input",
    "insensitive",
    "insert",
    "int",
    "integer",
    "intersect",
    "intersection",
    "interval",
    "into",
    "is",
    "isolation",
    "iterate",
    "join",
    "key",
    "language",
    "large",
    "last",
    "lateral",
    "leading",
    "left",
    "less",
    "level",
    "like",
    "like_regex",
    "limit",
    "ln",
    "local",
    "localtime",
    "localtimestamp",
    "locator",
    "lower",
    "map",
    "match",
    "max",
    "member",
    "method",
    "min",
    "minute",
    "mod",
    "modifies",
    "modify",
    "module",
    "month",
    "multiset",
    "names",
    "national",
    "natural",
    "nchar",
    "nclob",
    "new",
    "next",
    "no",
    "none",
    "normalize",
    "not",
    "null",
    "nullif",
    "numeric",
    "object",
    "occurrences_regex",
    "octet_length",
    "of",
    "old",
    "on",
    "only",
    "open",
    "operation",
    "option",
    "or",
    "order",
    "ordinality",
    "out",
    "outer",
    "output",
    "overlaps",
    "overlay",
    "pad",
    "parameter",
    "parameters",
    "partial",
    "partition",
    "pascal",
    "path",
    "percent_rank",
    "percentile_cont",
    "percentile_disc",
    "position",
    "position_regex",
    "postfix",
    "precision",
    "prefix",
    "preorder",
    "prepare",
    "preserve",
    "primary",
    "prior",
    "privileges",
    "procedure",
    "public",
    "range",
    "read",
    "reads",
    "real",
    "recursive",
    "ref",
    "references",
    "referencing",
    "regr_avgx",
    "regr_avgy",
    "regr_count",
    "regr_intercept",
    "regr_r2",
    "regr_slope",
    "regr_sxx",
    "regr_sxy",
    "regr_syy",
    "relative",
    "release",
    "restrict",
    "result",
    "returns",
    "revoke",
    "right",
    "role",
    "rollback",
    "rollup",
    "routine",
    "row",
    "rows",
    "savepoint",
    "schema",
    "scope",
    "scroll",
    "search",
    "second",
    "section",
    "select",
    "sensitive",
    "sequence",
    "session",
    "session_user",
    "set",
    "sets",
    "similar",
    "size",
    "smallint",
    "some",
    "space",
    "specific",
    "specifictype",
    "sql",
    "sqlca",
    "sqlcode",
    "sqlerror",
    "sqlexception",
    "sqlstate",
    "sqlwarning",
    "start",
    "state",
    "statement",
    "static",
    "stddev_pop",
    "stddev_samp",
    "structure",
    "submultiset",
    "substring",
    "substring_regex",
    "sum",
    "symmetric",
    "system",
    "system_user",
    "table",
    "temporary",
    "terminate",
    "than",
    "then",
    "time",
    "timestamp",
    "timezone_hour",
    "timezone_minute",
    "to",
    "trailing",
    "transaction",
    "translate",
    "translate_regex",
    "translation",
    "treat",
    "trim",
    "uescape",
    "under",
    "union",
    "unique",
    "unknown",
    "unnest",
    "update",
    "upper",
    "usage",
    "user",
    "using",
    "value",
    "values",
    "var_pop",
    "var_samp",
    "varchar",
    "variable",
    "varying",
    "view",
    "when",
    "whenever",
    "where",
    "width_bucket",
    "window",
    "with",
    "within",
    "without",
    "work",
    "write",
    "xmlagg",
    "xmlattributes",
    "xmlbinary",
    "xmlcast",
    "xmlcomment",
    "xmlconcat",
    "xmldocument",
    "xmlelement",
    "xmlexists",
    "xmlforest",
    "xmliterate",
    "xmlnamespaces",
    "xmlparse",
    "xmlpi",
    "xmlquery",
    "xmlserialize",
    "xmltable",
    "xmltext",
    "xmlvalidate",
    "year",
    "zone",
    "false",
    "true"
  )
}
